spring:
  datasource:
    url: jdbc:h2:file:./db/taskmanager
    driverClassName: org.h2.Driver
    username: sa
    password: pass

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
